spring.application.name=ApiGateway
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webmvc.discovery.locator.enabled=true
spring.cloud.gateway.server.webmvc.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webmvc.routes[0].id=notification-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://notification-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/users/**